export default {
    dict: {
        'ACTIVITY': 'Activities',
        'ACCOUNT': 'Account',
        'ACTION': 'Action',
        'ACTIVATION': 'Activation',
        'ACCESS': 'Access',
        'ADJUST': 'Adjust',
        'ADD_VALUE': 'Add Value',
        'ADD_SIDE': 'Add Side',
        'ADDRESS': 'Address',
        'ADJUST_TIP': 'Adjust Tip',
        'ASIAN': 'Asian',
        'AUTO_LOGOUT': 'Auto Logout',
        'AUTO_COMPLETE': 'Auto Complete',
        'ALL_RECORDS': 'All Records',
        'ANY_QTY': 'Any Qty',
        'APPETIZER': 'Appertizer',
        'API_KEY': 'API Key',
        'ALIES': 'Alies',
        'APPLY': 'Apply',
        'AREA': 'Area',
        'AUTH_CODE': 'Auth Code',
        'ALL_INVOICE': 'All Invoice',
        'ARRANGE': 'Arrange',
        'ASSIGN_WAITER': 'Assign Waiter',
        'ASSIGN': 'Assign',
        'AUTO_CHARGE': 'Auto Charge',
        'AUTO_CHARGE_ABOVE': '(N)Charge Above',
        'AUTO_CLEAN_TABLE': 'Auto Clear Table',
        'ACCEPT_CREDIT_CARD': 'Accept Credit Card',
        'ACCEPT_DELIVERY': 'Accept Delivery',
        'BAR': 'Bar',
        'BACK': 'Back',
        'BATCH': 'Batch',
        'BAD_CUST': 'Bad Cust.',
        'BLACK': 'Black',
        'BASIC_INFO': 'Basic Info',
        'BALANCE_DUE': 'Bal. Due',
        'BALANCE_REMAIN': 'Bal. Remain',
        'BINDING': 'Binding',
        'BUZZER': 'Buzzer',
        'BY_CALENDAR': 'Calendar',
        'BY_CASHIER': 'Cashier',
        'BY_DRIVER': 'Driver',
        'CATEGORY_REPORT': 'Category Report',
        'CASHFLOW': 'Cash Flow Control',
        'COMMAND': 'Command',
        'CHANGE': `Tendered $${d[0]}`,
        'CUST_PAID': `Customer Paid $${d[0]}`,
        'CLOCK_IN_REQ': 'Please Clock In First',
        'CUST_SEAT': 'Cust. Seat',
        'CONFIRM_ORD_TYP_SW': 'Confirm Change',
        'CONTAIN': 'Contain',
        'CAL_DIST': 'Calc. Dist.',
        'CALL_LOG': 'Call Log',
        'CASHDRAWER': 'Cash Drawer',
        'CUST_INFO': 'Cust. Info',
        'CATEGORY': 'Category',
        'CATEGORY_CN': 'Category(Sec.)',
        'CHANGE_DUE': 'Change Due',
        'CONFIRM_RPT_CC_RCPT': '打印信用卡收据',
        'CONTACT': 'Contact',
        'CODE_EDITOR': 'Code Editor',
        'CLEAR': 'Clear',
        'CLOCK_IN': 'Clock In',
        'CLOCK_OUT': 'Clock Out',
        'CLOCK_OUT_REPORT': 'Clock Out Report',
        'CLOCK_IN_CONFIRM': 'Clock In Confirm',
        'CLOCK_OUT_CONFIRM': 'Clock Out Confirm',
        'CASH_OUT': 'Cash Out',
        'CONTINUE': 'Continue',
        'CHECKSUM': 'Check Sum',
        'CONFIRM&PRINT': 'Yes & Print',
        'CONFIRM': 'Confirm',
        'CANCEL': 'Cancel',
        'CREATE': 'Create',
        'CITY': 'City',
        'CONFIG': 'Config',
        'CONNECT_DATABASE_FAILED': 'Can not connect to database.',
        'COURSE_TIME': 'Course Time',
        'CASH': 'Cash',
        'COMBINE_TABLE': 'Combine',
        'CREDIT_CARD': 'Credit Card',
        'CLEAR': 'Clear',
        'CC_DUP_TRANS': 'Trans Failed: Credit Card Duplicated',
        'CC_BAD_TRACK': 'Trans Failed: Can not READ track info',
        'CC_TRANS_ABORT': 'Trans aborted',
        'CC_EXP_INVALID': 'Trans Failed: Invalid Exp Date',
        'CC_DECLINED': 'Credit Card Delined',
        'CC_TIMEOUT': 'Trans Time Out',
        'CC_COMM_ERROR': 'Trans Failed: Please check your network connection',
        'CC_UNKNOWN': 'Trans Failed: An unknown error occured',
        'CC_NUMBER': 'Card Number',
        'CC_EXP': 'Exp Date',
        'CVV': 'Sercurity Code',
        'CANT_EDIT_VOIDED_ORDER': 'Can not edit voided order',
        'CANT_EDIT_VOIDED_ORDER_TIP': `This invoice has been voided by ${d[0]}, Pleaes recover it first`,
        'CALCULATE': 'Calc.',
        'CALLER_ID': 'Caller ID',
        'CHANGE_DATE': 'Change Date',
        'DATA': 'Data',
        'DATABASE': 'Database',
        'DISHONEST': 'Dishonest',
        'DURATION': 'Duration',
        'DISTANCE': 'Distance',
        'DONE': 'Done',
        'DEL_ITEM_TIP': `Are you sure you want to delete ${d[0]} from the list?`,
        'DP_CATEGORY': 'Display Category',
        'DELIVERY_FEE': 'Deli. Fee',
        'DELIVERY': 'Delivery',
        'DEL_ORDER': 'Del. Order',
        'DEBIT_CARD': 'Debet',
        'DELIVERY_INVOICE': 'Delivery Inv.',
        'DELETE': 'Delete',
        'DINE_IN': 'Dine In',
        'DISCOUNT': 'Discount',
        'DINE_IN_INVOICE': 'Dine In Invoice',
        'DINE_IN_DISABLED': 'Dine In Function is Disabled',
        'DYN_CHRG': 'Chrg by Mile',
        'DEL_ITEM_CONFIRM': 'Del. Item',
        'DRAWER_OPEN_PD': 'Can not OPEN cash drawer',
        'DRAWER_OPEN_PD_TIP': 'You can not access cash drawer, please contact store manager',
        'DELIVERY_FREE': 'Free Delivery',
        'DELIVERY_DURATION': 'Default Delivery Time',
        'DRIVER': 'Driver',
        'DESSERT': 'Dessert',
        'DISABLE_AUTO_ADD': 'Disable Auto Add',
        'ENABLE': 'Enable',
        'EXTRA': 'Extra',
        'EVEN_SPLIT': 'Even Split',
        'E_MAIL': 'Email',
        'EDIT_ITEM': 'Edit Item',
        'EDIT_ORDER': 'Edit Order',
        'EDITOR.HEADER.TAX': 'Edit Tax',
        'EDITOR.HEADER.UI': 'Edit Block',
        'EDITOR.HEADER.CATEGORY': 'Edit Category',
        'EDITOR.HEADER.REQUEST': 'Edit Request',
        'EDITOR.HEADER.ACTION': 'Edit Action',
        'EDITOR.HEADER.ITEM': 'Edit Item',
        'EDITOR.TAX.TIP': 'Apply Tax Base on Ticket Type',
        'EDITOR.HEADER.TEMPLATE': 'Edit Template',
        'EDITOR.TEMPLATE.MAX': 'Max Selection',
        'EDITOR.TEMPLATE.ADDITION': 'Addi. Cost',
        'EDITOR.TEMPLATE.STARTAT': '(n) Over',
        'EDITOR.EXIT.TIP': 'Exit Edit',
        'EXTENSION': 'Extension',
        'EXIT': 'Exit',
        'EDIT': 'Edit',
        'EMPLOYEE': 'Employee',
        'EXTEND': 'Extend',
        'ENTREE': 'Entree',
        'EXIT_CFM': 'Are you sure you want to exit?',
        'ERROR_CODE': `Error Code: ${d[0]}`,
        'FAR_AWAY': 'Far Away',
        'FRAUD': 'Fraud',
        'FORCE_CLEAR': 'Force Clear',
        'FIRST_PAGE': 'First Page',
        'FRI': 'Fri',
        'FONT': 'Font',
        'FONT_SIZE': 'Font Size',
        'GUEST_COUNT': 'Guest Count',
        'GET_PIN': 'PIN',
        'GOOGLE_MAP_SERVICE': 'Google Map',
        'GRATUITY': 'Gratuity',
        'GIFT_CARD': 'Gift',
        'GOOD_CUST': 'Good Cust.',
        'GC_SWIPE': 'Please Swipe Gift Card',
        'GC_ACTIVATION': 'This Gift Card requires activation',
        'GC_CARD_NUMBER': `Gift Card Number (${d[0]})`,
        'GIFT_CARD_SALES': 'Gift Card Sales',
        'GIFT_CARD_DEBET': 'Gift Card Debet',
        'HOTEL': 'Hotel',
        'HOLD': 'Hold',
        'HOUR': 'Hour',
        'HISTORY': 'History',
        'HOST_CONNECTED': 'Host connected...',
        'INVALID_DATE': '',
        'ICON': 'Icon',
        'INCOMING_CALL': 'Incoming call',
        'IMPOLITE': 'Impolite',
        'INIT_AMOUNT': 'Init. Amount',
        'ITEM_PENDING': `${d[0]} item(s)`,
        'ITEM_BUILDER': 'Item Builder',
        'ITEM_SEND': 'Item Send',
        'ISSUE_GC': 'Activating Gift Card',
        'ITEM_EDITOR': 'Item Editor',
        'INVOICE': 'Invoice',
        'ITEM': 'Item',
        'ITEM_INFO': 'Item Info',
        'IS_SPICY': 'Spicy',
        'ITEM_SIDE': 'Side(s)',
        'INVALID_VALUE': `${d[0]}'s format incorrect`,
        'INITIALIZING': 'Initializing...',
        'LAYOUT': 'Layout',
        'LESS': 'Less',
        'LOOKING_FOR_HOST': 'Finding Host...',
        'LOADING_CONFIG': 'Loading Configuration...',
        'LOADING_CONTENT': 'Loading Content...',
        'LOGOUT': 'Logout',
        'LANGUAGE': '语言',
        'LANG': 'Language',
        'LACK_INFO': 'Lack Info.',
        'LOUSY_CUST': 'Lousy',
        'MANAGER_CODE': 'Manager Code',
        'MARKER': 'Marker',
        'MANUAL_INPUT': 'Manual Input',
        'MINUTE': 'Minute',
        'MORE': 'More',
        'MODIFY': 'Modify',
        'MON': 'MON',
        'MODEL': 'Model',
        'MAC': 'MAC',
        'MENU': 'Menu',
        'MENU_ID': 'Menu ID',
        'MAX_ITEM': `Max ${d[0]}`,
        'MILE_COST': 'Cost per Mile',
        'MEXICAN': 'Mexican',
        'MIN_CASH_REQ': 'Min. Cash',
        'MIN_CREDIT_REQ': 'Min. Credit',
        'MAX_DELIVERY_RANGE': 'Max Range',
        'NEXT_PAGE': 'Next Page',
        'NEW_ORDER': 'New Order',
        'NAME': 'Name',
        'NOTE': 'Note',
        'NO_SERVICE': 'Black List',
        'NO_PREVS_ORDER': 'No Order Was Found',
        'NO_PREVS_ORDER_TIP': 'There is no invoice at selected date',
        'NEW_REPORT': 'New Report',
        'NEW_ITEM': 'New Item',
        'ORDER_PAYMENT_REMOVED': `You have remove #${d[0]} invoice payment record`,
        'ORDER_SPLIT': 'Order Split',
        'ORDER': 'Order',
        'PAYMENT': 'Payment',
        'PD_ACCESS': 'Access Denied',
        'PIN_INCORRECT': 'Pin Incorrect',
        'PICK_UP': 'Pick Up',
        'PHONE': 'Phone',
        'PHONE_RQD': 'Req. Phone',
        'PLACE_ORDER': 'Place Order',
        'PICKUP_DURATION': 'Default Pickup Time',
        'PRICE': 'Price',
        'PREV_PAGE': 'Prev Page',
        'PREFIX_VERB': 'Prefix',
        'POS_MAINTENANCE': 'POS Under Maintenance',
        'POS_MAINTENANCE_TIP': 'Please Be Patient!',
        'PRE_PAYMENT': 'Pre Payment',
        'PAYMENT_REMOVE': 'Remove Payment',
        'PAYMENT_REMOVE_CONFIRM': `Are you sure you want to remove ${d[0]} payment record?`,
        'PAYMENT_REMOVED': 'Payment record has been removed',
        'PASSWORD': 'Password',
        'PICK_UP_INVOICE': 'Pickup Invoice',
        'PRT_CFM': 'Print Confirm',
        'PYMT_F': 'Pay Failed',
        'PRT_ITEM_OR': 'Change Item Name',
        'PRIORITY': 'Priority',
        'PRINTER': 'Printer',
        'PRINT': 'Print',
        'PRINT_REDIRECT': 'Redirect Printer',
        'PRINT_REDIRECT_TO': 'To Printer',
        'PRINT_PRIMARY': 'Print Pri.',
        'PRINT_SECONDARY': 'Print Sec.',
        'PRINT_STORE': 'Store',
        'PRINT_ORDER_TYPE': 'Type',
        'PRINT_CUST_INFO': 'Cust.',
        'PRINT_PRICE': 'Price',
        'PRINT_PAYMENT': 'Payment',
        'PRINT_TIP_SUGG': 'Tip Sugg.',
        'PRINT_COUPON': 'Coupon',
        'PRINT_PRINTTIME': 'Time',
        'PRINT_ENLARGE_CUST_INFO': 'Enlarge',
        'PRINT_DUPLICATE': 'Duplicate',
        'PRINT_RECEIPT': 'Print Receipt',
        'PRINT_ALL': 'Print All',
        'PRINT_SETUP': 'Print Setup',
        'PRINT_REPORT': 'Print Report',
        'PRINT_TODAY_REPORT': 'Print today report',
        'PRIVATE_NUMBER': 'Private Number',
        'PROC_ON_TML': 'Please process in the terminal',
        'PRT_PRE_PAYT': 'Print Pre Payment',
        'PRT_PRE_PAYT_NA': 'Connot Print Pre Payment Ticket',
        'PRT_RCPT': 'Print Receipt',
        'PRT_BALANCE': 'Balance',
        'PRICE_EXTRA': 'Extra',
        'PORT': 'Port',
        'POLE_DISPLAY': 'Pole Display',
        'PRESET': 'Preset',
        'RESTART_APP': 'Restart',
        'RECEIPT_PRINTER': 'Receipt Printer',
        'REPORT_PD': 'Can not access report',
        'REPORT_PD_TIP': 'You have not right to acess Report, Please contact your store manager',
        'REPORT_COUNT_ITEM': 'Count items',
        'RECOVER_ORDER_CONFIRM': `Are you sure you want to recover ${d[0]} invoice`,
        'RECOVER_ORDER_CONFIRM_TIP': `This invoice has been voided by ${d[0]}. Reason:${d[1]}`,
        'REQUEST': 'Request',
        'RECOVER_ORDER': 'Recover',
        'RECEIPT': 'Receipt',
        'REPORT': 'Report',
        'REPORT_RANGE': 'Report Range',
        'REPORT_DETAILS': 'Report Details',
        'REASON_CUST_NO_SHOW': 'Cust. No Show',
        'REASON_CUST_CANCEL': 'Cancel by Cust.',
        'REASON_OP_CANCEL': 'Cancel by Operator',
        'REASON_MALICE_ORDER': 'Malice Order',
        'REASON_INVALID_ORDER': 'Invalid Order',
        'REASON_PAYMENT_ISSUE': 'Payment Issue Related',
        'REPORT_INFO': 'Report Content',
        'REOPEN_SETTLED_ORD': `Invoice #${d[0]} has been Settled & Closed`,
        'REOPEN_SETTLED_ORD_TIP': `You have remove ${d[0]} payment record before edit`,
        'REMOVE_PAYMENT': 'Remove Payment Record',
        'REFILL': 'Reload',
        'REDEMP': 'Redemp.',
        'ROUND_UP': 'RoundUp',
        'RETRY': 'Retry',
        'RESERVATION': 'Reservation',
        'RPT_CC_RCPT_TIP': `#${d[0]} Invoice is paid by Credit Card($${d[1]}). Do you need to reprint receipt?`,
        'RESTAURANT': 'Restaurant',
        'PERMISSION': 'Permission',
        'RSA_KEY': 'RSA Private',
        'ROLE': 'Role',
        'SALES': 'Sales',
        'SEARCH': 'Search',
        'SPLIT': 'Split',
        'SAVE': 'Save',
        'SUBTOTAL': 'Subtotal',
        'STORE_TYPE': 'Store Type',
        'STATION': 'Station',
        'SWITCH': 'Switch',
        'SWITCH_TABLE': 'Switch',
        'SPLIT_TABLE': 'Split',
        'SEAT': 'Seat',
        'SET_DISCOUNT': 'Set Discount',
        'STATE': 'State',
        'SINGLE': 'Single',
        'SAT': 'SAT',
        'SUN': 'SUN',
        'SEPARATE': 'Separate',
        'STATUS': 'Status',
        'SECOND_PAGE': 'Second Page',
        'SET_DRIVER': `Set Driver`,
        'SELF_INPUT_PRICE': 'Self Input',
        'SETTLE': 'Settle',
        'SET_GUEST': 'Set Guest',
        'SET_TABLE': 'Set Table',
        'SET_TIP': 'Set Tip',
        'SET_DEFAULT': 'Set Default',
        'SET_GRATUITY': 'Set Gratuity',
        'STUFF_BANK': 'Stuff Bank',
        'SEAT': 'Seat',
        'SEAT_ORDER': 'Seat Order',
        'SORT': 'Sort',
        'STA_UNREG': 'Station Unregistered',
        'STA_REG_F': 'Station Registing Failed',
        'STA_TERM_NA': 'There is no terminal attach to this Station',
        'SECURITY': 'Security',
        'SELECT_QTY': `Please Select ${d[0]}`,
        'SECTION': 'Section',
        'STARTER': 'Starter',
        'STATION_RECORDS': 'Current',
        'STATION.TERM.TIP': 'Set up credit card terminal',
        'STATION.POLEDISPLAY.TIP': 'Set up pole display',
        'STATION.POLEDISPLAY.FIRSTLINE': 'First Line',
        'STATION.POLEDISPLAY.SECONDLINE': 'Second Line',
        'SHUTDOWN': 'Shutdown',
        'STORE': 'Store',
        'SORT_ITEM': 'Sorting',
        'SETTING': 'Setting',
        'SETTING.HEAD.TITLE': 'UnitedPOS Setting',
        'SETTING.STORE.TIP': 'Basic · Station · Tax · Seat',
        'SETTING.MENU.TIP': 'Menu · Sorting',
        'SETTING.THIRDPARTY.TIP': 'Third Party Program · Intergration',
        'SETTING.SEAT.TIP': 'Seats · Sorting',
        'SETTING.ONLINE.TIP': 'Online Order Configuration',
        'SETTING.USERS.TIP': 'Permission · Time Card Report',
        'SETTING.PRINT.TIP': 'Printer · Style Control',
        'SETTING.DATABASE.TIP': 'Customer · Call Log · Address',
        'SETTING.SYSTEM.TIP': 'Update · Backup · Reset',
        'SETTING.SALES.TIP': 'Sales Report · Gift Card',
        'SETTING.TEMPLATE.TIP': 'Item template setup',
        'SETTING.EXIT.TIP': 'Exit Setup',
        'SETTING_UPDATED': 'New configuration has been saved',
        'SETTING.PRINT.CONTROL': 'Print style Control',
        'SETTING.PRINT.PRINT': 'Printer print',
        'SETTING.PRINT.DOUBLE': 'Double print',
        'SETTING.AUTOCHARGE.TIP': 'Setup auto charge condition',
        'SETTING.ONLINE.TIP': 'Setup online order service',
        'SETTING.OPERATOR.PIN_DUPLICATE': 'This pin is conflict with other operator. Please consider other pin',
        'SETTING.OPERATOR.NO_PIN': 'Must have a pin',
        'STATISTIC': 'Stat.',
        'SENT_RPT_VIA_EMAIL': 'Send Email',
        'SUMMARY': 'Summary',
        'TIP_CASH_IN_OUT': 'Cash inflow/outflow control setting ',
        'THIRD_PARTY': 'Third Party',
        'TIP': 'Tip',
        'TAX': 'Tax',
        'TOTAL': 'Total',
        'TERM_REPORT': 'Terminal Report',
        'TUE': 'TUE',
        'TAG': 'Tag',
        'TIMER': 'Timer',
        'THU': 'THU',
        'TITLE': 'Title',
        'TRANSACTION': 'Trans.',
        'SUBTITLE': 'Subtital',
        'SUBITEM': 'Subitem',
        'ROUTE': 'Route',
        'TABLE_EDITOR': 'Table Editor',
        'TABLE_INFO': 'Table Info',
        'TABLE_CLEAR': 'Clear Table',
        'TABLE_CLEAR_F': 'Can not Clear table info',
        'TABLE_SWITCH_F': 'Can not Swith table',
        'TABLE_SWITCH': 'Switch Table',
        'TABLE_CFM_SWITCH': 'Confirm Switch',
        'TAX_RATE': 'Tax Rate',
        'TAX_FREE': 'Tax Free',
        'TAX_CLASS': 'Tax Class',
        'TAX_GROUP': 'Tax Group',
        'TAX_BEFORE_DISC': 'Tax Before Disc.',
        'TAX_BEFORE_CREDIT': 'Tax Before Credit',
        'TEMPLATE': 'Template',
        'TERM': 'Terminal',
        'TERM_INIT': `Terminal ${d[0]} initializing...`,
        'TERM_COMM': `Communicating with ${d[0]}...`,
        'TERM_MANUAL': `Please insert credit card now ${d[0]}`,
        'TERM_ABORT': 'Aborting transaction...',
        'TERM_INIT_F': `${d[0]} initial failed`,
        'TERM_TIMEOUT': 'Terminal time out',
        'TERM_BATCH_CLOSE': 'Batch Confirm',
        'TERM_CONFIRM_ADJUST': 'Tip Adjust Confirm',
        'TERM_VOID_SALE': 'Void Credit Sale',
        'TERM_NA': 'Terminal Not Available',
        'TERM_BATCH_DISABLE': 'Batch Function Not Available',
        'TIP_TAX_ADVICE': 'Please consult your accountant before edit',
        'TIP_TAX_GROUP': 'Create a tax group apply multiple tax',
        'TIP_FOR_SMS_ALERT': 'SMS Service',
        'TIP_CALC_DISTANCE': 'Distance Calc.',
        'TIP_REMAIN_ITEM': `Remaind ${d[0]} Item(s)`,
        'TIP_NO_REMAIN_ITEM': 'All Items are printed',
        'TIP_PRINT_RESULT': `Sending ${d[0]} Item(s) to Kitchen`,
        'TIP_PRE_PAYT': `Are you sure to print table ${d[0]} Pre Payment ticket?`,
        'TIP_FORCE_CLEAR_TABLE': `${d[0]} is operating table ${d[1]}, Are you sure to clear table status?`,
        'TIP_REG_STA': 'You have to registered this station',
        'TIP_REASON': `Failed: ${d[0]}`,
        'TIP_TABLE_CLEAR': `Are you sure you want to clear table ${d[0]} info?`,
        'TIP_TABLE_CLEAR_F': `You can not clear table ${d[0]} info`,
        'TIP_PRT_RCPT': 'Are you sure to print Receipt ticket?',
        'TIP_ORDER_SETTLED': 'This Invoice is closed',
        'TIP_AUTO_LOGOUT': `System auto logout due to ${d[0]}(s) timeout`,
        'TIP_CALC_CITY_REQ': 'City Field Required',
        'TIP_DINE_IN_ENABLE': '若想使用此功能，请去 设置->餐馆->堂吃->座位 选择开启',
        'TIP_CLOCK_IN': 'Please Clock In First',
        'TIP_TABLE_MUST_EMPTY': 'Target table must be empty',
        'TIP_SWITCH_CFM': `Are you sure to switch ${d[0]} to ${d[1]} ?`,
        'TIP_SELECT_TABLE': 'Please select one empty table',
        'TIP_PRT_SPOOLER': `Scheduled print ${d[0]} (${d[1]} after). Are you sure to print it right now?`,
        'TIP_EXIT_CFM': 'Unsave order will be removed',
        'TIP_CASH_OUT': `Please ensure customer cash all out($${d[0]})`,
        'TIP_WITHDRAW': `Please take cash above to customer`,
        'TIP_TERM_TIMEOUT': `Please check terminal IP address (IP: ${d[0]})`,
        'TIP_TERM_BATCH_CLOSE': 'Please ensure you have entered all tips',
        'TIP_TERM_ADJUST_TIP': `Tip adjust to $${d[0]}, Total:$${d[1]}`,
        'TIP_SAVE_CONFIG': 'You have made changes. Please save configuration',
        'TIP_CHARGE_BACK': 'Charge Back Risk',
        'TIP_TERM_VOID_SALE': `同时也会移除 ${d[0]}号 订单的付款记录`,
        'TIP_CLOCK_IN': `You clock in at ${d[0]} `,
        'TIP_CLOCK_OUT': `YOu clock in at ${d[0]}. Total work time: ${d[1]}`,
        'TIP_CLOCK_IN_REQ': 'Please Clock in First',
        'TIP_PD_ACCESS': 'You do not have permission todo so. Please contact store manager',
        'TIME_CARD': 'Time Card',
        'TABLE_LAYOUT': 'Table',
        'TIME_ZONE': 'Time Zone',
        'THIRD_PAGE': 'Third Page',
        'TAX_CALC': 'Tax Calculation',
        'TERMINAL': 'Terminal',
        'ORDER_SETTLED': 'Order settled',
        'OPEN_CD': 'Open Cash Drawer',
        'OPEN_CD_PRT': 'Open CD & Print',
        'ONLINE_ORDER': 'Online Order',
        'ORD_TYP_SW': `Order type change from ${d[0]} to ${d[1]}`,
        'OP_LIST': 'Operator List',
        'OP': 'Operator',
        'OPTION': 'Option',
        'OPERATOR.PERMISSION.TIP': 'Setup operator permission',
        'OPERATOR.TIMECARD.TIP': 'Employee time card report',
        'UNVOID_ORDER_CONFIRM': 'Are you sure to recover this invoice',
        'UNAVOIDABLE_PREVS_ORDER': 'Unable to void prevs order',
        'UNAVOIDABLE_PREVS_ORDER_TIP': 'You can not void other date invoice',
        'UNABLE_ACCESS': 'Unable access',
        'VOID_ORDER_CONFIRM': `Void #${d[0]} ${d[1]} Invoice`,
        'VOID_ORDER_CONFIRM_TIP': 'You can not edit invoice once you voided order',
        'VOID_SETTLED_ORD': 'Order is Settled',
        'VOID_SETTLED_ORD_TIP': `You have to remove ${d[0]} payment record before void it`,
        'VOID_ORDER_PD': 'Can not Void Order',
        'VOID_ORDER_PD_TIP': 'You do not have permission todo so. Please contact store manager',
        'VOID_REASON': 'Void Reason',
        'VOID': 'Void',
        'VIEW': 'View',
        'VIEW_LIST': 'List',
        'UI': 'UI',
        'SYSTEM': 'System',
        'UNABLE_SEND': 'Unable Send',
        'UNPAID_INVOICE': 'Unpaid Order',
        'US_EN': 'English',
        'QTY': 'Qty',
        'WALK_IN': 'Walk In',
        'WALK_IN_INVOICE': 'WalkIn Invoice',
        'WEN': 'WEN',
        'WHITE': 'White',
        'WITHDRAW': `Cash $ ${d[0]}`,
        'WAIT_QUEUE': 'Wait Queue',
        'WEIGHT_SCALE': 'Weight Scale',
        'ZIP_CODE': 'Zip Code',
        'ZH_CN': 'Chinese'
    }
}